config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/signup", to: "users#new"
  post "/signup",  to: "users#create"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, except: [:index, :show, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy, :index]
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= t "partial.footer.The" %>
    <%= link_to t("partial.footer.rails"),
      href="http://www.railstutorial.org/" %>
    <%= t "parital.footer.by" %>
    <%= link_to t("partial.footer.micheal"),
      href="http://www.michaelhartl.com/" %>
  </small>
  <nav>
    <ul>
      <li><%= link_to t("partial.footer.about"), about_path %></li>
      <li><%= link_to t("partial.footer.contact"), contact_path %></li>
      <li><%= link_to t("partial.footer.news"),
        href="http://news.railstutorial.org/" %>
      </li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t("partial.header.sample_app"), root_path, class: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t("partial.header.home"), root_path %></li>
        <li><%= link_to t("partial.header.help"), help_path %></li>
        <% if logged_in? %>
          <li><%= link_to t("partial.header.users"), users_path %></li>
          <li class="dropdown">
            <%= link_to "#", class: "dropdown-toggle",
              data: {toggle: "dropdown"} do %>
              <%= t "partial.header.account" %>
              <b class="caret"></b>
            <% end %>
            <ul class="dropdown-menu">
              <li><%= link_to t("partial.header.profile"), current_user %></li>
              <li><%= link_to t("partial.header.setting"),
                edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to t("partial.header.logout"), logout_path,
                  method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t("partial.header.login"), login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag "application", media: "all",
  "data-turbolinks-track": "reload" %>
<%= javascript_include_tag "application",
  "data-turbolinks-track": "reload" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <%= render "layouts/rails_default" %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render "layouts/footer" %>
      <%= debug params if Rails.env.development? %>
    </div>
  </body>
</html>